repos:
  - repo: https://github.com/python/black
    rev: 23.9.1
    hooks:
    - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.292"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
