dependencies:
  # command line stuff
  - click
  - coverage
  - pyshp
  - tqdm
  - pandas
  # image work
  - pillow
  - psycopg
  # Fast geojson reading
  - pyogrio
  # For testing
  - pytest
  - pytest-cov
  - pytest-runner
  # interpolation
  - scipy
  # GIS work
  - shapely
  - sqlalchemy
  # daily auto-tweeter
  - tweepy
  - reportlab
