[tool.ruff]
line-length = 79
lint.select = [
    "B",  # bugbear
    "E",
    "F",
    "I",
    # "PD",  # pandas
]
target-version = "py39"

# per memory issues microsoft/pylance-release/issues/5739
[tool.pyright]
autoSearchPaths = false
exclude = ["data/", "prj2wepp/"]
ignore = ["data/", "prj2wepp/"]
