[tool.ruff]
line-length = 79
lint.select = [
    "B",  # bugbear
    "E",
    "F",
    "I",
    # "PD",  # pandas
    "T20",  # print
]
target-version = "py39"

[tool.ruff.lint.per-file-ignores]
"scripts/**/*.py" = [
    "T20",  # print
]

# per memory issues microsoft/pylance-release/issues/5739
[tool.pyright]
autoSearchPaths = false
exclude = ["data/", "prj2wepp/"]
ignore = ["data/", "prj2wepp/"]
