
name: pydep CI
on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: ["3.8", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3

    - name: Add /etc/hosts entries
      run: |
        cat .github/workflows/etchosts.txt | sudo tee -a /etc/hosts

    - name: Build and test
      run: |
        git clone --depth 1 https://github.com/akrherz/iem-database.git database
        git clone --depth 1 https://github.com/akrherz/ci_tooling.git .ci_tooling
        . .ci_tooling/postgres.sh
        . .ci_tooling/miniconda.sh
        . .ci_tooling/memcached.sh
        python -m pip install . --upgrade --no-deps
        export PATH="/usr/lib/postgresql/14/bin:$PATH"
        cd database; sh bootstrap.sh
        python schema_manager.py
        cd ..
        coverage run --source=pydep setup.py test
        coverage xml

    - name: Upload codecov
      if: ${{ matrix.PYTHON_VERSION == '3.8' }}
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
