
name: pydep CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    defaults:
      run:
        # Ensures environment gets sourced right
        shell: bash -e -l {0}
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Min supported is 3.10
        # IEM runs 3.11
        # 3.13 is the latest release
        PYTHON_VERSION: ["3.10", "3.11", "3.13"]
    env:
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    steps:
    - uses: actions/checkout@v5

    - name: Run IEM Database container
      run: |
        docker run -d --name iem_database -p 5432:5432 ghcr.io/akrherz/iem_database:test_data
        until docker exec iem_database pg_isready -h localhost; do
          sleep 6
        done

    - name: Run Memcached container
      run: |
        docker run -d --name iem_memcached -p 11211:11211 memcached:1.6.9

    - name: Add /etc/hosts entries
      run: |
        cat .github/workflows/etchosts.txt | sudo tee -a /etc/hosts

    # setup conda-forge with micromamba
    - name: Setup Python
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        condarc: |
          channels:
            - conda-forge
            - defaults
        create-args: >-
          python=${{ env.PYTHON_VERSION }}
        environment-name: prod
        cache-environment: true

    # None at this time
    #- name: Install Python Dependencies via pip
    #  run: python -m pip install -r pip_requirements.txt

    - name: Setup paths
      run: sh .github/setuppaths.sh

    - name: Setup data
      run: sh .github/setupdata.sh

    - name: Build and test
      run: |
        python -m pip install . --upgrade --no-deps
        python -m pytest --cov=pydep tests
        python -m coverage xml

    - name: Upload codecov
      if: ${{ env.PYTHON_VERSION == '3.13' }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
